import json
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

from character_info.char_sprites import get_char_sprites, Sprite
from utils.data_utils import sprite_root
from utils.wiki_utils import save_page

VENDOR_DIR = Path("vendor/groundingdino")
CONFIG_PATH = VENDOR_DIR / "groundingdino/config/GroundingDINO_SwinT_OGC.py"
WEIGHTS_PATH = VENDOR_DIR / "weights/groundingdino_swint_ogc.pth"
RESULT_FILE = sprite_root / "face_data.json"

TEXT_PROMPT = "face"
BOX_THRESHOLD = 0.25
TEXT_THRESHOLD = 0.20


def pick_representative_sprite(sprites: list[Sprite]) -> Path | None:
    if len(sprites) == 1:
        return sprites[0].combined
    for s in sprites:
        if s.number > 1 and s.combined is not None:
            return s.combined
    return None


def detect_faces():
    if not VENDOR_DIR.exists():
        subprocess.run(["git", "clone", "https://github.com/idea-research/groundingdino"], cwd=VENDOR_DIR.parent)
    sys.path.insert(0, str(VENDOR_DIR))
    from groundingdino.util.inference import load_model, load_image, predict

    if RESULT_FILE.exists():
        with open(RESULT_FILE, "r", encoding="utf-8") as f:
            result: dict[str, dict[str, list[float]]] = json.load(f)
    else:
        result = {}

    model = load_model(str(CONFIG_PATH), str(WEIGHTS_PATH))
    model = model.to('cuda:0')

    all_sprites = get_char_sprites()

    for char_name, variants in all_sprites.items():
        if char_name not in result:
            result[char_name] = {}
        for variant_name, sprites in variants.items():
            if variant_name in result[char_name]:
                continue

            image_path = pick_representative_sprite(sprites)
            if image_path is None or not image_path.exists():
                print(f"Warning: no image for {char_name}/{variant_name}")
                continue

            image_source, image = load_image(str(image_path))
            boxes, logits, phrases = predict(
                model=model,
                image=image,
                caption=TEXT_PROMPT,
                box_threshold=BOX_THRESHOLD,
                text_threshold=TEXT_THRESHOLD,
            )

            if len(boxes) == 0:
                print(f"Warning: no face detected for {char_name}/{variant_name}")
                continue

            height, width, _ = image_source.shape
            cx, cy, bw, bh = boxes[0]
            x1 = (cx - bw / 2) * width
            y1 = (cy - bh / 2) * height
            x2 = (cx + bw / 2) * width
            y2 = (cy + bh / 2) * height

            result[char_name][variant_name] = [
                round(x1.item()),
                round(y1.item()),
                round(x2.item()),
                round(y2.item()),
            ]

    result = {k: v for k, v in result.items() if v}

    RESULT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(RESULT_FILE, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=4, ensure_ascii=False)
    print(f"Saved face data to {RESULT_FILE}")


def load_face_data() -> dict[str, dict[str, list[int]]]:
    with open(RESULT_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def sanitize_css_class(char_name: str, variant_name: str) -> str:
    sanitized = char_name.replace("'", "")
    sanitized = re.sub(r'[^a-zA-Z0-9]', '-', sanitized)
    sanitized = re.sub(r'-+', '-', sanitized)
    sanitized = sanitized.strip('-')
    return f"sprite-face-{sanitized}-{variant_name}"


ASSUMED_FACE_SIZE = 170.0
TARGET_FACE_SIZE = 40.0
CIRCLE_DIAMETER = 60.0


def get_sprite_dimensions(char_name: str, variant_name: str) -> tuple[int, int]:
    char_dir = sprite_root / char_name
    matches = sorted(char_dir.glob(f"{char_name}_{variant_name}_*.png"))
    if not matches:
        raise FileNotFoundError(f"No sprite image for {char_name}/{variant_name}")
    img = Image.open(matches[0])
    return img.size


def generate_face_css():
    face_data = load_face_data()
    scale = TARGET_FACE_SIZE / ASSUMED_FACE_SIZE

    lines = [
        "/* Auto-generated by StellaSoraBot. */",
        f"/* Circle: {CIRCLE_DIAMETER:.0f}px | Assumed face: {ASSUMED_FACE_SIZE:.0f}px | Target face: {TARGET_FACE_SIZE:.0f}px */",
        "",
        ".message-row .messenger-profile-picture img { height: auto; flex-shrink: 0; }",
        "",
    ]

    for char_name in sorted(face_data.keys()):
        variants = face_data[char_name]
        lines.append(f"/* === {char_name} === */")
        for variant_name in sorted(variants.keys()):
            bbox = variants[variant_name]
            x1, y1, x2, y2 = bbox
            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2

            try:
                img_w, img_h = get_sprite_dimensions(char_name, variant_name)
            except FileNotFoundError as e:
                print(f"Warning: {e}")
                continue

            width = round(img_w * scale)
            # Flexbox centering absorbs half the margin, so double the offset
            margin_left = round((img_w - 2 * cx) * scale)
            margin_top = round((img_h - 2 * cy) * scale)

            cls = sanitize_css_class(char_name, variant_name)
            lines.append(
                f".{cls} img {{ width: {width}px; margin-left: {margin_left}px; margin-top: {margin_top}px; }}"
            )
        lines.append("")

    css = "\n".join(lines)
    save_page("Template:Messenger/face.css", css, "update face positioning CSS")


def sprite_face_main():
    detect_faces()
    generate_face_css()


def main():
    sprite_face_main()


if __name__ == '__main__':
    main()
